# Generated by Django 5.0.7 on 2024-10-27 14:35

import apps.accounts.validation
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('image', models.ImageField(upload_to='category/', verbose_name='Фото услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Profile')),
                ('phone_number', models.CharField(blank=True, error_messages={'unique': 'Пользователь с таким номером телефона уже существует.'}, help_text='Обязательное поле. Должно содержать от 10 цифр (0700 123 456) до 12 цифр (996 700 123 456', max_length=13, null=True, unique=True, validators=[apps.accounts.validation.PhoneNumberValidator()], verbose_name='Номер телефона')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_doctor', models.BooleanField(default=False, verbose_name='doctor')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Опыт (лет)')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(verbose_name='Количество отзывов')),
                ('consultation_cost', models.CharField(max_length=50, verbose_name='Стоимость консультации')),
                ('description', models.TextField(verbose_name='Описание врача')),
                ('image', models.ImageField(upload_to='doctors/', verbose_name='Фото врача')),
                ('education', models.TextField(verbose_name='Образование и квалификации')),
                ('treatment_approach', models.TextField(verbose_name='Подход к лечению')),
                ('experience', models.TextField(verbose_name='Опыт работы')),
                ('skills', models.TextField(verbose_name='Навыки и опыт')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='accounts.category', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Докторы',
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='medical history')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
    ]
