# Generated by Django 5.0.7 on 2024-10-16 13:07

import apps.accounts.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patientprofile_age_patientprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'Пользователь с таким номером телефона уже существует.'}, help_text='Обязательное поле. Должно содержать от 10 цифр (0700 123 456) до 12 цифр (996 700 123 456', max_length=13, null=True, unique=True, validators=[apps.accounts.validation.PhoneNumberValidator()], verbose_name='Номер телефона'),
        ),
    ]
