# Generated by Django 5.0.7 on 2024-11-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone_number_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='stars',
            field=models.SmallIntegerField(max_length=1, verbose_name='Колличество звёзд'),
        ),
    ]
