# Generated by Django 5.0.7 on 2024-11-13 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_reviews_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='password',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
