# Generated by Django 5.0.7 on 2024-10-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='description',
            field=models.TextField(default=1, verbose_name='description'),
            preserve_default=False,
        ),
    ]
