# Generated by Django 5.0.7 on 2024-10-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doctorprofile_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'verbose_name': 'Доктор', 'verbose_name_plural': 'Докторы'},
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_cost',
            field=models.CharField(default=1, max_length=50, verbose_name='Стоимость консультации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='education',
            field=models.TextField(default=1, verbose_name='Образование и квалификации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=1, verbose_name='Опыт (лет)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(default=1, upload_to='doctors/', verbose_name='Фото врача'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='reviews_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество отзывов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='skills',
            field=models.TextField(default=1, verbose_name='Навыки и опыт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty',
            field=models.CharField(default=1, max_length=100, verbose_name='Специализация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='treatment_approach',
            field=models.TextField(default=1, verbose_name='Подход к лечению'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='description',
            field=models.TextField(verbose_name='Описание врача'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience',
            field=models.TextField(verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='rating',
            field=models.FloatField(verbose_name='Рейтинг'),
        ),
    ]
