# Generated by Django 5.0.7 on 2024-11-18 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_doctorprofile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='gender',
        ),
    ]
