# Generated by Django 5.0.7 on 2024-11-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='consul_type',
            field=models.CharField(default=1, max_length=250, verbose_name='Тип консультации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='wh_number',
            field=models.CharField(default=1, max_length=15, verbose_name='Номер WhatsApp'),
            preserve_default=False,
        ),
    ]
