# Generated by Django 5.0.7 on 2024-11-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_consul_type_consultation_wh_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-date'], 'verbose_name': 'consultation', 'verbose_name_plural': 'consultations'},
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='date_time',
        ),
        migrations.AddField(
            model_name='consultation',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата записи'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время записи'),
        ),
    ]
